// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// apply_duration_thresh
NumericVector apply_duration_thresh(NumericVector tseries, double thresh);
RcppExport SEXP _stayinalive_apply_duration_thresh(SEXP tseriesSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tseries(tseriesSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_duration_thresh(tseries, thresh));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stayinalive_apply_duration_thresh", (DL_FUNC) &_stayinalive_apply_duration_thresh, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_stayinalive(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
