# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Apply a drought duration threshold to a time series
#'
#' Eliminate any droughts with a duration less than the specified threshold.
#'
#' Note that this function modifies the tseries argument.  This is done in order to
#' avoid the overhead of copying the vector.  Since our intended use is to \code{apply}
#' this to the rows of a matrix, this is of no consequence, since apply will do its own
#' copying.  However, if the function is used on a vector, users should be prepared for
#' this un-R-like behavior.
#'
#' @param tseries (NumericVector) Time series of drought duration (time steps
#' not in drought have a duration of zero).  CAUTION:  This time series will be
#' modified.  See details.
#' @param thresh (double) Minimum drought duration.  Shorter droughts will
#' be eliminated.
#' @return (NumericVector) Time series with droughts shorter than the threshold removed.
#' @export
apply_duration_thresh <- function(tseries, thresh) {
    .Call('_stayinalive_apply_duration_thresh', PACKAGE = 'stayinalive', tseries, thresh)
}

